import { useEffect, useState } from "react";
import { Check, Copy, Link2, Plug, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card } from "@/components/ui/card";
import { newszxcnService } from "@/services/newszxcn-service";
import { copyTextToClipboard } from "@/shared/browser/clipboard";

const copy = { title: "NewSzxcn 共享收件箱", help: "在系统设置中配置。家庭共享输入邮箱地址即可搜索并生成短链接。", api: "API 地址", token: "lq_... API 令牌（留空保持不变）", save: "保存", test: "测试连接", search: "输入邮箱或搜索邮箱", select: "选择邮箱", thirty: "30 分钟", hour: "1 小时", sixHours: "6 小时", day: "24 小时", week: "7 天", expires: "过期时间（可选）", create: "生成短链接", created: "已创建链接", duplicate: "复制", reset: "重置链接", revoke: "撤销" };
export function NewSzxcnAdminPanel() {
  const [baseUrl, setBaseUrl] = useState("https://mail.newszxcn.com"); const [token, setToken] = useState(""); const [status, setStatus] = useState(""); const [mailboxes, setMailboxes] = useState<Array<{ id: string; address: string }>>([]); const [mailboxId, setMailboxId] = useState(""); const [mailboxQuery, setMailboxQuery] = useState(""); const [folderIds] = useState<string[]>(["fld_inbox"]); const [links, setLinks] = useState<any[]>([]); const [windowMinutes, setWindowMinutes] = useState(30); const [expiresAt, setExpiresAt] = useState("");
  const load = async () => { try { const config = await newszxcnService.getConfig(); if (config.integration) setBaseUrl(config.integration.baseUrl); const current = await newszxcnService.links(); setLinks(current.links); } catch { /* admin API rejects non-admins */ } };
  useEffect(() => { void load(); }, []);
  const test = async () => { setStatus("正在测试连接..."); try { const result = await newszxcnService.test(); setMailboxes((result.mailboxes ?? []) as Array<{ id: string; address: string }>); setStatus(`连接成功，共 ${result.mailboxes?.length ?? 0} 个邮箱`); } catch (error) { setStatus(error instanceof Error ? error.message : "连接失败"); } };
  const save = async () => { try { await newszxcnService.saveConfig(token ? { baseUrl, token } : { baseUrl }); setToken(""); setStatus("配置已加密保存"); } catch (error) { setStatus(error instanceof Error ? error.message : "保存失败"); } };
  const create = async (input = { mailboxId, folderIds, windowMinutes, expiresAt: expiresAt ? new Date(expiresAt).toISOString() : null }) => { if (!input.mailboxId) return; try { const result = await newszxcnService.create(input); if (result.link?.shortUrl) await copyTextToClipboard(result.link.shortUrl); setStatus("短链接已创建并复制"); await load(); } catch (error) { setStatus(error instanceof Error ? error.message : "创建失败"); } };
  const reset = async (link: any) => { try { await newszxcnService.revoke(link.id); await create({ mailboxId: link.mailboxId, folderIds: link.folderIds, windowMinutes: link.windowMinutes, expiresAt: link.expiresAt }); setStatus("链接已重置，旧链接已失效"); } catch (error) { setStatus(error instanceof Error ? error.message : "重置失败"); } };
  const visibleMailboxes = mailboxes.filter((box) => !mailboxQuery.trim() || box.address.toLowerCase().includes(mailboxQuery.trim().toLowerCase()));
  return <Card className="mt-6 border-primary/20 p-5"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold">{copy.title}</h2><p className="text-sm text-muted-foreground">{copy.help}</p></div><Plug className="h-5 w-5 text-primary" /></div><div className="mt-4 grid gap-3 md:grid-cols-[1fr_1fr_auto]"><Input value={baseUrl} onChange={(event) => setBaseUrl(event.target.value)} placeholder={copy.api} /><Input value={token} onChange={(event) => setToken(event.target.value)} placeholder={copy.token} type="password" /><div className="flex gap-2"><Button onClick={() => void save()}>{copy.save}</Button><Button variant="outline" onClick={() => void test()}>{copy.test}</Button></div></div><div className="mt-3 text-sm text-muted-foreground">{status}</div>{mailboxes.length ? <div className="mt-5 border-t pt-4"><div className="grid gap-3 md:grid-cols-[1fr_1fr_1fr_auto]"><Input value={mailboxQuery} onChange={(event) => setMailboxQuery(event.target.value)} placeholder={copy.search} /><select className="h-10 rounded-md border bg-background px-3" value={mailboxId} onChange={(event) => setMailboxId(event.target.value)}><option value="">{copy.select}</option>{visibleMailboxes.map((box) => <option key={box.id} value={box.id}>{box.address}</option>)}</select><select className="h-10 rounded-md border bg-background px-3" value={windowMinutes} onChange={(event) => setWindowMinutes(Number(event.target.value))}><option value={30}>{copy.thirty}</option><option value={60}>{copy.hour}</option><option value={360}>{copy.sixHours}</option><option value={1440}>{copy.day}</option><option value={10080}>{copy.week}</option></select><Button onClick={() => void create()}><Link2 className="mr-2 h-4 w-4" />{copy.create}</Button></div><Input className="mt-3" type="datetime-local" value={expiresAt} onChange={(event) => setExpiresAt(event.target.value)} placeholder={copy.expires} /></div> : null}{links.length ? <div className="mt-5 space-y-2 border-t pt-4"><h3 className="font-medium">{copy.created}</h3>{links.map((link) => <div key={link.id} className="flex items-center gap-2 rounded-md border px-3 py-2 text-sm"><span className="min-w-0 flex-1 truncate">{link.shortUrl}</span><Button size="icon" variant="ghost" title={copy.duplicate} onClick={() => void copyTextToClipboard(link.shortUrl)}><Copy className="h-4 w-4" /></Button>{link.status === "active" ? <><Button size="sm" variant="outline" onClick={() => void reset(link)}>{copy.reset}</Button><Button size="icon" variant="ghost" title={copy.revoke} onClick={async () => { await newszxcnService.revoke(link.id); await load(); }}><Trash2 className="h-4 w-4 text-destructive" /></Button></> : <Check className="h-4 w-4 text-muted-foreground" />}</div>)}</div> : null}</Card>;
}
