import { useCallback, useEffect, useState } from "react";
import { ArrowLeft, Download, FileText, Inbox, Mail, Paperclip, RefreshCw, ShieldCheck } from "lucide-react";
import { useParams } from "react-router";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { newszxcnService } from "@/services/newszxcn-service";

type Message = { id: string; subject?: string; from?: string; fromName?: string; receivedAt?: string; snippet?: string; hasAttachments?: boolean };
type Attachment = { id: string; filename?: string; sizeBytes?: number };
type Detail = Message & { folder?: string; bodyText?: string; bodyHtml?: string; attachments?: Attachment[] };
type ListResult = { items?: Message[]; mailboxAddress?: string; windowMinutes?: number; nextCursor?: string | null };
const copy = { denied: "无权访问共享收件箱", inbox: "共享收件箱", readonly: "只读", refresh: "刷新", latest: "最新邮件", mailUnit: "封", loading: "正在加载邮件...", empty: "当前范围内没有邮件", unknown: "未知发件人", noSubject: "（无主题）", select: "选择一封邮件查看详情", back: "返回列表", body: "邮件正文", attachments: "附件", readonlyHelp: "只读页面，无法回复、转发、删除或修改邮件。", loadingDetail: "正在加载邮件内容..." };

function rangeLabel(minutes?: number) { if (!minutes) return "只读分享"; if (minutes < 60) return `最近 ${minutes} 分钟`; if (minutes < 1440) return `最近 ${minutes / 60} 小时`; return `最近 ${minutes / 1440} 天`; }
function timeLabel(value?: string) { if (!value) return ""; const date = new Date(value); return Number.isNaN(date.getTime()) ? "" : date.toLocaleString("zh-CN", { hour12: false }); }
function mailDocument(html: string) {
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src data:; style-src 'unsafe-inline'; font-src data:; base-uri 'none'; form-action 'none'"><style>html,body{margin:0;background:#fff;color:#111827}body{box-sizing:border-box;padding:20px;font:14px/1.65 Arial,sans-serif;overflow-wrap:anywhere}*,*:before,*:after{box-sizing:border-box}img,table{max-width:100%}img{height:auto}pre{white-space:pre-wrap}@media(max-width:600px){body{padding:16px}}</style></head><body>${html}</body></html>`;
}

export default function SharedInbox() {
  const { shortKey = "" } = useParams();
  const [list, setList] = useState<ListResult>({}); const [selectedId, setSelectedId] = useState(""); const [detail, setDetail] = useState<Detail | null>(null); const [mobileDetail, setMobileDetail] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const messages = list.items ?? [];
  const load = useCallback(async () => { setLoading(true); setError(""); try { const result = await newszxcnService.publicMessages(shortKey) as ListResult; setList(result); const first = result.items?.[0]; if (first) setSelectedId((current) => current || first.id); } catch { setError("分享链接无效、已关闭或已过期"); } finally { setLoading(false); } }, [shortKey]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { if (!selectedId) { setDetail(null); return; } void newszxcnService.publicMessage(shortKey, selectedId).then((result) => setDetail(result as Detail)).catch(() => setDetail(null)); }, [shortKey, selectedId]);
  const srcDoc = detail?.bodyHtml ? mailDocument(detail.bodyHtml) : "";
  if (error) return <main className="grid min-h-svh place-items-center bg-background p-6 text-foreground"><section className="max-w-md text-center"><ShieldCheck className="mx-auto h-10 w-10 text-muted-foreground" /><h1 className="mt-4 text-xl font-semibold">{copy.denied}</h1><p className="mt-2 text-sm text-muted-foreground">{error}</p></section></main>;
  return <main className="flex h-svh min-h-0 flex-col overflow-hidden bg-background text-foreground">
    <header className="flex min-h-16 shrink-0 items-center justify-between gap-3 border-b bg-card px-4 sm:px-6"><div className="flex min-w-0 items-center gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-md bg-primary text-primary-foreground"><Mail className="h-5 w-5" /></span><div className="min-w-0"><h1 className="truncate text-sm font-semibold sm:text-base">{list.mailboxAddress || copy.inbox}</h1><p className="truncate text-xs text-muted-foreground">{rangeLabel(list.windowMinutes)}</p></div></div><div className="flex items-center gap-2"><span className="hidden items-center gap-1 text-xs text-muted-foreground sm:flex"><ShieldCheck className="h-4 w-4" />{copy.readonly}</span><Button variant="outline" size="icon" onClick={() => void load()} disabled={loading} aria-label={copy.refresh}><RefreshCw className={cn("h-4 w-4", loading && "animate-spin")} /></Button></div></header>
    <div className="grid min-h-0 flex-1 md:grid-cols-[minmax(18rem,23rem)_minmax(0,1fr)]">
      <section className={cn("min-h-0 border-r bg-card", mobileDetail && "hidden md:block")}><div className="flex h-12 items-center justify-between border-b px-4"><span className="flex items-center gap-2 text-sm font-semibold"><Inbox className="h-4 w-4" />{copy.latest}</span><span className="text-xs text-muted-foreground">{messages.length} {copy.mailUnit}</span></div><div className="h-[calc(100%-3rem)] overflow-y-auto">{loading ? <div className="p-8 text-center text-sm text-muted-foreground">{copy.loading}</div> : messages.length === 0 ? <div className="p-10 text-center text-sm text-muted-foreground">{copy.empty}</div> : messages.map((message) => <button key={message.id} type="button" className={cn("block w-full border-b p-4 text-left hover:bg-muted/50", selectedId === message.id && "bg-muted")} onClick={() => { setSelectedId(message.id); setMobileDetail(true); }}><div className="flex items-center justify-between gap-3"><span className="min-w-0 truncate text-sm font-medium">{message.fromName || message.from || copy.unknown}</span><time className="shrink-0 text-xs text-muted-foreground">{timeLabel(message.receivedAt)}</time></div><p className="mt-1 flex items-center gap-1 truncate text-sm"><span className="truncate">{message.subject || copy.noSubject}</span>{message.hasAttachments ? <Paperclip className="h-3.5 w-3.5 shrink-0" /> : null}</p><p className="mt-1 truncate text-xs text-muted-foreground">{message.snippet}</p></button>)}</div></section>
      <section className={cn("min-h-0 overflow-y-auto", !mobileDetail && "hidden md:block")}>{!selectedId ? <div className="grid h-full place-items-center text-sm text-muted-foreground">{copy.select}</div> : <article className="mx-auto max-w-4xl p-4 sm:p-7"><Button variant="ghost" size="sm" className="-ml-2 mb-3 md:hidden" onClick={() => setMobileDetail(false)}><ArrowLeft className="mr-1 h-4 w-4" />{copy.back}</Button>{detail ? <><h2 className="wrap-break-word text-xl font-semibold sm:text-2xl">{detail.subject || copy.noSubject}</h2><div className="mt-4 border-b pb-4 text-sm"><p className="font-medium">{detail.fromName || detail.from}</p><p className="break-all text-muted-foreground">{detail.fromName ? detail.from : ""}</p><p className="mt-1 text-muted-foreground">{timeLabel(detail.receivedAt)}{detail.folder ? ` · ${detail.folder}` : ""}</p></div><div className="mt-5 overflow-hidden rounded-md border bg-white text-black">{detail.bodyHtml ? <iframe title={copy.body} sandbox="" referrerPolicy="no-referrer" srcDoc={srcDoc} className="block min-h-112 w-full border-0 bg-white" /> : <pre className="whitespace-pre-wrap wrap-break-word p-4 font-sans text-sm leading-7 sm:p-5">{detail.bodyText || detail.snippet}</pre>}</div>{detail.attachments?.length ? <div className="mt-5"><h3 className="mb-2 text-sm font-semibold">{copy.attachments}</h3><div className="divide-y rounded-md border">{detail.attachments.map((attachment) => <a key={attachment.id} href={`/api/shared-inbox/${encodeURIComponent(shortKey)}/attachments/${encodeURIComponent(attachment.id)}`} className="flex min-h-12 items-center gap-2 px-3 py-2 text-sm hover:bg-muted/40"><FileText className="h-4 w-4" /><span className="min-w-0 flex-1 truncate">{attachment.filename || copy.attachments}</span><Download className="h-4 w-4" /></a>)}</div></div> : null}<p className="mt-6 flex items-center gap-2 text-xs text-muted-foreground"><ShieldCheck className="h-4 w-4" />{copy.readonlyHelp}</p></> : <div className="py-16 text-center text-sm text-muted-foreground">{copy.loadingDetail}</div>}</article>}</section>
    </div>
  </main>;
}
