import { useEffect, useState } from "react";
import { useParams } from "react-router";
import { Mail, Paperclip, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { newszxcnService } from "@/services/newszxcn-service";

type Message = { id?: string; subject?: string; from?: string; fromName?: string; receivedAt?: string; snippet?: string; hasAttachments?: boolean };
export default function SharedInbox() {
  const { shortKey = "" } = useParams(); const [messages, setMessages] = useState<Message[]>([]); const [selected, setSelected] = useState<Record<string, unknown> | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = async () => { setLoading(true); setError(""); try { const result = await newszxcnService.publicMessages(shortKey); setMessages(((result as { messages?: unknown[] }).messages ?? []) as Message[]); } catch (e) { setError(e instanceof Error ? e.message : "链接已失效"); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [shortKey]);
  const open = async (id: string) => { const result = await newszxcnService.publicMessage(shortKey, id); setSelected((result as { message: Record<string, unknown> }).message); };
  return <main className="min-h-screen bg-muted/30 p-4 sm:p-8"><div className="mx-auto max-w-5xl"><header className="mb-6 flex items-center justify-between"><div><h1 className="text-2xl font-semibold">共享收件箱</h1><p className="text-sm text-muted-foreground">仅显示授权窗口内的邮件</p></div><Button variant="outline" size="icon" onClick={() => void load()} aria-label="刷新"><RefreshCw className="h-4 w-4" /></Button></header>{error ? <Card className="p-8 text-center text-destructive">{error}</Card> : <div className="grid gap-3">{loading ? <Card className="p-8 text-center">正在加载邮件...</Card> : messages.length === 0 ? <Card className="p-8 text-center text-muted-foreground"><Mail className="mx-auto mb-2 h-8 w-8" />暂无邮件</Card> : messages.map((message) => <button key={message.id} type="button" className="rounded-lg border bg-background p-4 text-left transition hover:border-primary hover:shadow-sm" onClick={() => message.id && void open(message.id)}><div className="flex items-start justify-between gap-4"><div className="min-w-0"><h2 className="truncate font-medium">{message.subject || "(无主题)"}</h2><p className="mt-1 text-sm text-muted-foreground">{message.fromName || message.from || "未知发件人"}</p><p className="mt-2 line-clamp-2 text-sm text-muted-foreground">{message.snippet}</p></div><div className="shrink-0 text-xs text-muted-foreground">{message.receivedAt ? new Date(message.receivedAt).toLocaleString() : ""}{message.hasAttachments ? <Paperclip className="ml-2 inline h-3.5 w-3.5" /> : null}</div></div></button>)}</div>}{selected ? <div className="fixed inset-0 z-50 bg-black/40 p-4" onClick={() => setSelected(null)}><Card className="mx-auto mt-10 max-h-[80vh] max-w-3xl overflow-auto p-6" onClick={(event) => event.stopPropagation()}><h2 className="text-xl font-semibold">{String(selected["subject"] || "(无主题)")}</h2><p className="mt-2 text-sm text-muted-foreground">{String(selected["from"] || "")}</p><pre className="mt-6 whitespace-pre-wrap font-sans text-sm">{String(selected["bodyText"] || selected["snippet"] || "")}</pre></Card></div> : null}</div></main>;
}
